django/Metis/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('wui.urls', namespace='wui')),
    path('', include('api.urls', namespace='api')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/apps/wui/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
import wui.views as views

app_name = 'wui'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^image$', views.list_image, name='list_image'),
    re_path(r'^image/new$', views.new_image, name='new_image'),
    re_path(r'^image/(?P<id>\d+)$', views.edit_image, name='edit_image'),
    re_path(r'^image/(?P<image_id>\d+)/bbox/new$', views.edit_bbox_image, name='new_bbox_image'),
    re_path(r'^image/(?P<image_id>\d+)/bbox/(?P<bbox_id>\d+)$', views.edit_bbox_image, name='edit_bbox_image'),
]

django/templates/edit_bbox_image.html
{% load static %}
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/tagify.css' %}">
<script src="{% static 'js/jQuery.tagify-2.30.0.min.js' %}"></script>

<div class="container">
  <ul>
    <li>
      <a href="{% url 'wui:index' %}">Index</a>
    <li>
      <a href="{% url 'wui:new_image' %}">Upload New Image/s</a>
    <li>
      <a href="{% url 'wui:list_image' %}">Browse Images</a>
  </ul>

  <form id="edit_bbox_form" method="POST">
    {% csrf_token %}
    {{ edit_bbox_form.post_type }}
  </form>

  <form id="delete_bbox_form" method="POST">
    {% csrf_token %}
    {{ delete_bbox_form.post_type }}
  </form>

  <p>
    {{ edit_bbox_form.tags }}

  <div style="display: flex;">
    <table style="padding: .5em 1em;">
      <tr>
        <td>
          Left
          <td>
          {{ edit_bbox_form.left }}
        <td>
          Right
        <td>
          <input id="right_input" type="number">
      <tr>
        <td>
          Top
        <td>
        {{ edit_bbox_form.top }}
        <td>
          Bottom
        <td>
          <input id="bottom_input" type="number">
    </table>

    <table style="padding: .5em 1em;">
      <tr>
        <td>
          Center X
        <td>
          <input id="center_x_input" type="number">
        <td>
          Center Y
        <td>
          <input id="center_y_input" type="number">
      <tr>
        <td>
          Width
        <td>
          {{ edit_bbox_form.width }}
        <td>
          Height
        <td>
          {{ edit_bbox_form.height }}
    </table>
  </div>

  <p>
    <button type="submit" form="edit_bbox_form">Save</button>
    <button type="reset" form="edit_bbox_form">Reset</button>
{% if bbox %}
    <button id="delete_bbox_button" type="submit" form="delete_bbox_form">Delete this Bounding box</button>
{% endif %}

    <a href="{% url 'wui:edit_image' image.id %}">Back to Image</a>

  <p>
    <table>
      <tr>
        <td>
          Line Width
        <td>
          <input id="line_width_input" type="number" value="1" min="1", max="8">
    </table>

  <div class="bbox-image-preview-box-wrapper">
    <div class="bbox-image-preview-box">
      <img class="bbox-image-preview" src="{{ image.image_file.url }}" data-width="{{ image.image_file.width }}" data-height="{{ image.image_file.height }}">
      <canvas id="bbox_canvas" class="canvas-full" width="{{ image.image_file.width }}" height="{{ image.image_file.height }}"></canvas>
    </div>
  </div>

  <script>
    $('#tags_input').tagify({
      'maxTags': 1,
    });

    var bboxCanvas = $('#bbox_canvas');
    var isDrawingBBox = false;
    var startX = 0;
    var startY = 0;
    var endX = 0;
    var endY = 0;
    var mouseX = 0;
    var mouseY = 0;

    var leftInput = $('#left_input');
    var topInput = $('#top_input');
    var rightInput = $('#right_input');
    var bottomInput = $('#bottom_input');

    var centerXInput = $('#center_x_input');
    var centerYInput = $('#center_y_input');
    var widthInput = $('#width_input');
    var heightInput = $('#height_input');

    var lineWidthInput = $('#line_width_input');

    var lineWidth = lineWidthInput.val();
    lineWidthInput.on('change', function() {
      var val = parseInt(lineWidthInput.val());
      if (val) {
        lineWidth = val;
        updateCanvas();
      }
    });

    leftInput.on('change', onBBoxSideFieldUpdated);
    topInput.on('change', onBBoxSideFieldUpdated);
    rightInput.on('change', onBBoxSideFieldUpdated);
    bottomInput.on('change', onBBoxSideFieldUpdated);

    centerXInput.on('change', onBBoxCenterSizeFieldUpdated);
    centerYInput.on('change', onBBoxCenterSizeFieldUpdated);
    widthInput.on('change', onBBoxCenterSizeFieldUpdated);
    heightInput.on('change', onBBoxCenterSizeFieldUpdated);


    function onBBoxFieldUpdated() {
      setVirtualBBoxFieldsWithBBox();
      updateCanvas();
    }
    function onBBoxSideFieldUpdated() {
      var left = asInt(leftInput.val());
      var top = asInt(topInput.val());
      var right = asInt(rightInput.val());
      var bottom = asInt(bottomInput.val());

      var width = right - left;
      var height = bottom - top;
      var centerX = Math.round((left + right) / 2);
      var centerY = Math.round((top + bottom) / 2);

      centerXInput.val(centerX);
      centerYInput.val(centerY);
      widthInput.val(width);
      heightInput.val(height);

      updateCanvas();
    }
    function onBBoxCenterSizeFieldUpdated() {
      var centerX = asInt(centerXInput.val());
      var centerY = asInt(centerYInput.val());
      var width = asInt(widthInput.val());
      var height = asInt(heightInput.val());

      var left = Math.round(centerX - width/2);
      var top = Math.round(centerY - height/2);
      var right = Math.round(centerX + width/2);
      var bottom = Math.round(centerY + height/2);

      leftInput.val(left);
      topInput.val(top);
      rightInput.val(right);
      bottomInput.val(bottom);

      updateCanvas();
    }

    function asInt(val) {
      return parseInt(val);
    }
    function updateBBoxWithMouse() {
      var minX = Math.min(startX, endX);
      var maxX = Math.max(startX, endX);
      var minY = Math.min(startY, endY);
      var maxY = Math.max(startY, endY);

      var domWidth = bboxCanvas.width();
      var domHeight = bboxCanvas.height();

      var cvs = bboxCanvas[0];
      var cvsWidth = cvs.width;
      var cvsHeight = cvs.height;

      var scaleX = cvsWidth/domWidth;
      var scaleY = cvsHeight/domHeight;
      var scaleL = Math.sqrt(scaleX*scaleX + scaleY*scaleY);

      var minXInImage = minX * scaleX;
      var minYInImage = minY * scaleY;
      var maxXInImage = maxX * scaleX;
      var maxYInImage = maxY * scaleY;

      var widthInImage = maxXInImage - minXInImage;
      var heightInImage = maxYInImage - minYInImage;

      leftInput.val(Math.round(minXInImage));
      topInput.val(Math.round(minYInImage));
      rightInput.val(Math.round(maxXInImage));
      bottomInput.val(Math.round(maxYInImage));

      onBBoxSideFieldUpdated();
    }
    function updateCanvas() {
      var domWidth = bboxCanvas.width();
      var domHeight = bboxCanvas.height();

      var cvs = bboxCanvas[0];
      var cvsWidth = cvs.width;
      var cvsHeight = cvs.height;

      var scaleX = cvsWidth/domWidth;
      var scaleY = cvsHeight/domHeight;
      var scaleL = Math.sqrt(scaleX*scaleX + scaleY*scaleY);

      var left = leftInput.val();
      var top = topInput.val();
      var width = widthInput.val();
      var height = heightInput.val();

      var ctx = cvs.getContext('2d');

      ctx.clearRect(0, 0, cvsWidth, cvsHeight);
      ctx.beginPath();
      ctx.strokeStyle = 'rgb(255,0,255)';
      ctx.lineWidth = lineWidth * scaleL;
      ctx.rect(left, top, width, height);
      ctx.stroke();

    }

    bboxCanvas.on('mousedown', function(e) {
      mouseX = e.offsetX;
      mouseY = e.offsetY;

      startX = endX = mouseX;
      startY = endY = mouseY;
      isDrawingBBox = true;

      updateBBoxWithMouse();
    }).on('mousemove', function(e) {
      mouseX = e.offsetX;
      mouseY = e.offsetY;

      if (isDrawingBBox) {
        endX = mouseX;
        endY = mouseY;

        updateBBoxWithMouse();
      }

    }).on('mouseup', function(e) {
      mouseX = e.offsetX;
      mouseY = e.offsetY;

      if (isDrawingBBox) {
        endX = mouseX;
        endY = mouseY;

        isDrawingBBox = false;
        updateBBoxWithMouse();
      }

    });


    function initEditBBoxForm() {
      var left = asInt(leftInput.val());
      var top = asInt(topInput.val());
      var width = asInt(widthInput.val());
      var height = asInt(heightInput.val());

      var right = left + width;
      var bottom = top + height;
      var centerX = Math.round(left + width/2);
      var centerY = Math.round(left + width/2);

      centerXInput.val(centerX);
      centerYInput.val(centerY);
      rightInput.val(right);
      bottomInput.val(bottom);

      setTimeout(updateCanvas, 100);
    };

    initEditBBoxForm();

    $('#edit_bbox_form').on('reset', function() {
      setTimeout(initEditBBoxForm, 1);
    });

    $('#delete_bbox_button').on('click', function(e) {
      if (! confirm('Confirm to delete')) {
        e.preventDefault();
      }
    });

  </script>
</div>

django/templates/edit_image.html
{% load static %}
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/tagify.css' %}">
<script src="{% static 'js/jQuery.tagify-2.30.0.min.js' %}"></script>

<ul>
  <li>
    <a href="{% url 'wui:index' %}">Index</a>
  <li>
    <a href="{% url 'wui:new_image' %}">Upload New Image/s</a>
  <li>
    <a href="{% url 'wui:list_image' %}">Browse Images</a>
</ul>

<form id="delete_image_form" method="POST">
  {% csrf_token %}
  {{ delete_image_form.post_type }}
</form>

<form id="edit_image_form" method="POST">
  {% csrf_token %}
  {{ edit_image_form.post_type }}
</form>

<p>
  <button id="delete_image_button" type="submit" form="delete_image_form">Delete this Image</button>

<h2>Image</h2>
<div class="image-preview-box">
  <img class="image-preview" src="{{ image.image_display_file.url }}">
</div>

<p>
  {{ edit_image_form.source_page_url }}
  {{ edit_image_form.source_raw_url }}

<p>
  {{ edit_image_form.tags }}

<p>
  <button type="submit" form="edit_image_form" data-type="edit_image">Save</button>

<h3>Bounding Box</h3>
  <p>
    <a href="{% url 'wui:new_bbox_image' image.id %}">New Bounding Box for this Image</a>

<table border="1" cellpadding="3">
  <tr>
    <th>Tag
    <th>Area %
    <th>Menu
{% for bbox in image.bboxes.all %}
  <tr>
    <td>
      {{ bbox.tag.name }}
({% for tag in bbox.tag.tree %} {{ tag.name }} -> {% endfor %})
    <td>{{ bbox.area_percentage |floatformat }}
    <td>
      <a href="{% url 'wui:edit_bbox_image' image.id bbox.id %}">Edit</a>
{% endfor %}
</table>

<script>
  $('#delete_image_button').on('click', function(e) {
    if (! confirm('Confirm to delete')) {
      e.preventDefault();
    }
  });

  $('#tags_input').tagify();

</script>

django/templates/index.html
{% load static %}
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/tagify.css' %}">
<script src="{% static 'js/jQuery.tagify-2.30.0.min.js' %}"></script>

<ul>
  <li>
    <a href="{% url 'wui:index' %}">Index</a>
  <li>
    <a href="{% url 'wui:new_image' %}">Upload New Image/s</a>
  <li>
    <a href="{% url 'wui:list_image' %}">Browse Images</a>
</ul>

django/templates/list_image.html
{% load static %}
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/tagify.css' %}">
<script src="{% static 'js/jQuery.tagify-2.30.0.min.js' %}"></script>

<ul>
  <li>
    <a href="{% url 'wui:index' %}">Index</a>
  <li>
    <a href="{% url 'wui:new_image' %}">Upload New Image/s</a>
  <li>
    <a href="{% url 'wui:list_image' %}">Browse Images</a>
</ul>

<div class="image-list">
{% for image in images %}
  <div class="image-list-item">
    <a href="{% url 'wui:edit_image' image.id %}">
	<img src="{% if image.thumbnail_display %}{{ image.thumbnail_display.url }}{% endif %}">
    </a>
  </div>
{% endfor %}
</div>

django/templates/new_image.html
{% load static %}
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/tagify.css' %}">
<script src="{% static 'js/jQuery.tagify-2.30.0.min.js' %}"></script>

<ul>
  <li>
    <a href="{% url 'wui:index' %}">Index</a>
  <li>
    <a href="{% url 'wui:new_image' %}">Upload New Image/s</a>
  <li>
    <a href="{% url 'wui:list_image' %}">Browse Images</a>
</ul>

<form id="new_image_form" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
</form>

<p>
  Image File: {{ new_image_form.image }}

<p>
  {{ new_image_form.source_page_url }}
  {{ new_image_form.source_raw_url }}

<p>
  {{ new_image_form.tags }}

<p>
  <button type="submit" form="new_image_form">Submit</button>

<script>
  $('#tags_input').tagify();

</script>